steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/finventory-1776558252/web:latest'
      - '-t'
      - 'gcr.io/finventory-1776558252/web:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'apps/web'

images:
  - 'gcr.io/finventory-1776558252/web:latest'
  - 'gcr.io/finventory-1776558252/web:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
