steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=finventory-1776558252'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=AIzaSyBQxXiH3-vS9WMWCJ0C9wDqfRaQc29E6Cg'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=finventory-1776558252.firebaseapp.com'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=finventory-1776558252.firebasestorage.app'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=1776558252'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=1:1776558252:web:abc123'
      - '--build-arg'
      - 'VITE_API_URL=https://api-eodwatsp5q-uc.a.run.app'
      - '-t'
      - 'us-central1-docker.pkg.dev/finventory-1776558252/cloud-run-source-deploy/finventory-web:v3-21bins'
      - '-f'
      - 'apps/web/Dockerfile'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/finventory-1776558252/cloud-run-source-deploy/finventory-web:v3-21bins'

images:
  - 'us-central1-docker.pkg.dev/finventory-1776558252/cloud-run-source-deploy/finventory-web:v3-21bins'

options:
  logging: CLOUD_LOGGING_ONLY
