import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#4e3e00',
        'outline': '#707881',
        'on-secondary-container': '#773e01',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#ebd6c9',
        'surface-container-high': '#f9e4d7',
        'error': '#ba1a1a',
        'on-primary-fixed-variant': '#004a75',
        'surface-bright': '#fff8f5',
        'background': '#fff8f5',
        'inverse-surface': '#3a2e25',
        'tertiary': '#725c07',
        'on-primary-container': '#f7f9ff',
        'inverse-primary': '#95ccff',
        'surface-container-low': '#fff1e9',
        'on-surface-variant': '#404750',
        'secondary-fixed-dim': '#ffb77d',
        'on-background': '#241911',
        'on-primary-fixed': '#001d32',
        'surface-tint': '#00639a',
        'secondary-fixed': '#ffdcc3',
        'on-tertiary-fixed-variant': '#574500',
        'on-tertiary-fixed': '#231b00',
        'tertiary-container': '#c5a952',
        'on-primary': '#ffffff',
        'surface': '#fff8f5',
        'tertiary-fixed': '#ffe085',
        'outline-variant': '#c0c7d1',
        'on-error': '#ffffff',
        'on-surface': '#241911',
        'error-container': '#ffdad6',
        'surface-container-highest': '#f3dfd1',
        'surface-variant': '#f3dfd1',
        'inverse-on-surface': '#ffede2',
        'primary-fixed-dim': '#95ccff',
        'primary': '#005f93',
        'surface-container': '#ffeadc',
        'primary-fixed': '#cde5ff',
        'secondary': '#8c4f14',
        'tertiary-fixed-dim': '#e2c46a',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#6e3900',
        'secondary-container': '#fdac6a',
        'primary-container': '#1e78b4',
        'on-secondary-fixed': '#2f1500',
        'sunset-yellow': '#FFCA4D',
        'vibrant-teal': '#00ACC1',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
        accent: ['Caveat', 'cursive'],
      },
    },
  },
  plugins: [],
} satisfies Config
